import type { GlobalThemeOverrides } from 'naive-ui'
export const naiveThemeOverrides: GlobalThemeOverrides = {
    common: {
        borderRadius: '5px',
        primaryColor: '#f49a27',
        primaryColorHover: '#ffb454',
        primaryColorPressed: '#d77f14',
    },
    Input: {
        border: '1px solid var(--color-garage-border)',
        borderHover: '1px solid var(--color-garage-orange)',
        borderFocus: '1px solid var(--color-garage-orange)',
        boxShadowFocus: '0 0 0 2px rgba(244, 154, 39, 0.18)',
        color: 'var(--color-garage-input)',
        colorFocus: 'var(--color-garage-input)',
        textColor: '#f8fafc',
        placeholderColor: 'var(--color-garage-muted)',
        heightLarge: '56px',
        fontSizeLarge: '16px',
        paddingLarge: '0 20px',
    },
    Button: {
        color: 'transparent',
        colorHover: '#151923',
        colorPressed: '#151923',
        colorFocus: '#151923',
        colorPrimary: 'var(--color-garage-orange)',
        colorHoverPrimary: 'var(--color-garage-orange-soft)',
        colorPressedPrimary: 'var(--color-garage-orange-deep)',
        colorFocusPrimary: 'var(--color-garage-orange)',
        textColor: '#f8fafc',
        textColorHover: '#f8fafc',
        textColorPressed: '#f8fafc',
        textColorFocus: '#f8fafc',
        textColorPrimary: '#0e1014',
        textColorHoverPrimary: '#0e1014',
        textColorPressedPrimary: '#0e1014',
        textColorFocusPrimary: '#0e1014',
        border: '1px solid var(--color-garage-border)',
        borderHover: '1px solid var(--color-garage-border-soft)',
        borderPressed: '1px solid var(--color-garage-border-soft)',
        borderFocus: '1px solid var(--color-garage-border-soft)',
        borderPrimary: '1px solid var(--color-garage-orange)',
        borderHoverPrimary: '1px solid var(--color-garage-orange-soft)',
        borderPressedPrimary: '1px solid var(--color-garage-orange-deep)',
        borderFocusPrimary: '1px solid var(--color-garage-orange)',
        heightLarge: '54px',
        fontSizeLarge: '14px',
        fontWeight: '500',
        fontWeightStrong: '600',
    },
    Divider: {
        color: 'var(--color-garage-border)',
        textColor: 'var(--color-garage-muted)',
        fontWeight: '400',
    },
}
